name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make deploy script executable
        run: chmod +x deploy.sh

      - name: Deploy application
        run: ./deploy.sh